documentation: 
- documentation/**/*

System tests: 
- systemtest/**/*
- test/**/*

cluster operator:
- cluster-operator/**/*

topic operator:
- topic-operator/**/*

user operator:
- user-operator/**/*

docker images:
- docker-images/**/*
