# Triggers
# This pipeline will be triggered manually for a release or by github comment
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'

jobs:
  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'acceptance'
      display_name: 'acceptance-bundle'
      test_case: '.*ST'
      groups: 'acceptance'
      cluster_operator_install_type: 'bundle'
      timeout: 240


