# Triggers
# This pipeline will be triggered manually for a release or by github comment
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'
      -
# Regression tests are split into 6 jobs because of timeout set to 360 minutes for each job
jobs:
  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_kafka'
      display_name: 'regression-bundle I. - kafka + oauth'
      test_case: 'kafka/**/*ST,!kafka/dynamicconfiguration/**/*ST,security/oauth/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_security'
      display_name: 'regression-bundle II. - security'
      test_case: 'security/**/*ST,!security/oauth/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_connect_tracing_watcher'
      display_name: 'regression-bundle III. - connect + tracing + watcher'
      test_case: 'connect/**/*ST,tracing/**/*ST,watcher/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_operators'
      display_name: 'regression-bundle IV. - operators'
      test_case: 'operators/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_rollingupdate_watcher'
      display_name: 'regression-bundle V. - rollingupdate'
      test_case: 'rollingupdate/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_mirrormaker'
      display_name: 'regression-bundle VI. - mirrormaker + dynamicconfiguration'
      test_case: 'mirrormaker/**/*ST,kafka/dynamicconfiguration/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_all_remaining'
      display_name: 'regression-bundle VII. - remaining system tests'
      test_case: '!kafka/**/*ST,!mirrormaker/**/*ST,!connect/**/*ST,!security/**/*ST,!operators/**/*ST,!rollingupdate/**/*ST,!watcher/**/*ST,!tracing/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360
