name: Documentation checks

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -DskipTests package
    - name: Ls
      run: ls -l
    - name: Check docs I
      run: .travis/check_docs.sh
    - name: Check docs II
      run: make docu_check
