name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: Assign labels based on changed files
      uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Assign labels based on size
      uses: pascalgn/size-label-action@v0.0.6
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
